### ISSUE TITLE
Missing code file

### ISSUE THREAD

**Issue by lfj95** [ZhengxiangShi/StepGame#1]
In the final part of the readme, it's said to generate more samples using 'python parameterized_step_game_8relation.py --seed 123.' However, I couldn't find the 'parameterized_step_game_8relation.py' file in the code list. Could you consider updating it?

**Comment by ShiZhengyan** [comment]
Thanks for your interest in our work. I have added `parameterized_step_game_8relation.py` into the `Code` folder. Please let me know if you have any other questions.

Zhengxiang
