### ISSUE TITLE
Suspected errors in template

### ISSUE THREAD

**Issue by jinulee-v** [ZhengxiangShi/StepGame#2]
Hello, thanks for the great dataset!

I suspect that several errors are present in the template (StepGame/Code/template.py).
If I understood the codes and the templates correctly,  `right`, `below`, `upper-right`, `upper-left` templates should denote `BB is right/.../upper-left to AA`. However, some templates seem to be inversed.

Suspicious templates:
- AA is at the bottom of BB and is on the same vertical plane. (below)
- AA presents below BB. (below)
- Object A is above object BB and to the right of it, too. (upper-right)
- AA is diagonally to the upper right of BB. (upper-right)

I'm not sure if there is more, but I guess that this is probably it.

**Comment by ShiZhengyan** [comment]
Hi Jinu,

Thank you so much for your message and for pointing it out. I have updated the `template.py` file. 

Best regards,
Zhengxiang

**Comment by jinulee-v** [comment]
@ZhengxiangShi , thank you for your kind and instant response.

Actually, this error also affects the actual datasets. This example is from TrainVersion/qa1_tst.json:
![image](https://github.com/ZhengxiangShi/StepGame/assets/76199370/5db9aa23-9e5b-440b-bca1-456d6d9d49c0)

You might notice that the label should be "below", not "above" in this case.

I manually cleansed the dataset for my experiments, by excluding these errorneous templates.
However, I believe that you should consider re-publishing the dataset after cleansing (both in Github and Huggingface!), as [the authors of CLUTRR did](https://koustuvsinha.com/post/zero_shot_clutrr/).

Note: [This ACL 2023 findings paper](https://aclanthology.org/2023.findings-acl.321.pdf) also has discovered the template errors, so maybe they should get some credit. They claim that ~10.7% of the test sets have errorneous labels.

**Comment by ShiZhengyan** [comment]
Thanks a lot for pointing it out, especially for the ACL paper. You are right, and we will have a look and correct them.

**Comment by ShiZhengyan** [comment]
Solved by the latest commit.
